## Experiment series 1 - Regular Dataset - Result Analysis

### Original Sampleset: [Located here](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/LibraryManagement_authentic_sampleset_no_space.xlsx)

*P labeled 15 , NP labeled 85 from LibraryManagemet OM Data obtained from TradeMaker.*





[Result 2 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-2-c.csv)

In [32]:
# Experiment 2 Classification Report (Regular Dataset - 6 OM combined)
# Result from 101 samples Librarymanagement 
# Result set URL:

# P Labeled 1 and NP labeled 99 from RNN Results



import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-2-c.csv" )
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y ,test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[39  0]
 [ 1  0]]
              precision    recall  f1-score   support

          NP       0.97      1.00      0.99        39
           P       0.00      0.00      0.00         1

    accuracy                           0.97        40
   macro avg       0.49      0.50      0.49        40
weighted avg       0.95      0.97      0.96        40



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#Experiment 1 does not have concrete result so it is not present in the notebook. 

[Result 3 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-3-c.csv
)

In [33]:
# Experiment 3 Classification Report (Regular Dataset - 6 OM combined)
# Result from 101 samples 
# P Labeled 19 and NP labeled 79 from RNN Results



import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-3-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[18 14]
 [ 1  7]]
              precision    recall  f1-score   support

          NP       0.95      0.56      0.71        32
           P       0.33      0.88      0.48         8

    accuracy                           0.62        40
   macro avg       0.64      0.72      0.59        40
weighted avg       0.82      0.62      0.66        40



[Result 4 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-4-c.csv 
)

In [34]:
# Experiment 4 Classification Report (Regular Dataset - 6 OM combined)
# Result from 101 samples 
# P Labeled 23 and NP labeled 77 from RNN Results


import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-4-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[24 11]
 [ 1  4]]
              precision    recall  f1-score   support

          NP       0.96      0.69      0.80        35
           P       0.27      0.80      0.40         5

    accuracy                           0.70        40
   macro avg       0.61      0.74      0.60        40
weighted avg       0.87      0.70      0.75        40



[Result 5 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-5-c.csv
)

In [35]:
# Experiment 5 Classification Report (Regular Dataset - 6 OM combined)
# Result from 101 samples 
# P Labeled 10 and NP labeled 90 from RNN Results



import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-5-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[30  4]
 [ 6  0]]
              precision    recall  f1-score   support

          NP       0.83      0.88      0.86        34
           P       0.00      0.00      0.00         6

    accuracy                           0.75        40
   macro avg       0.42      0.44      0.43        40
weighted avg       0.71      0.75      0.73        40



In [ ]:
#Experiment 6 does not have concrete result so it is not present in the notebook. 

[Result 7 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-7-c.csv 
)


In [36]:
# Experiment 7 Classification Report (Regular Dataset - 7 OM combined)
# Result from 101 samples 
# P Labeled 33 and NP labeled 67 from RNN Results


import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-7-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[15 10]
 [ 5 10]]
              precision    recall  f1-score   support

          NP       0.75      0.60      0.67        25
           P       0.50      0.67      0.57        15

    accuracy                           0.62        40
   macro avg       0.62      0.63      0.62        40
weighted avg       0.66      0.62      0.63        40



[Result 8 CSV File](https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-8-c.csv 
)

In [37]:
# Experiment 8 Classification Report (Regular Dataset - 7 OM combined)
# Result from 101 samples 
# P Labeled 32 and NP labeled 68 from RNN Results



import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-8-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[18  8]
 [ 7  7]]
              precision    recall  f1-score   support

          NP       0.72      0.69      0.71        26
           P       0.47      0.50      0.48        14

    accuracy                           0.62        40
   macro avg       0.59      0.60      0.59        40
weighted avg       0.63      0.62      0.63        40



[Result 9 CSV File](#https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-9-c.csv 
)

In [38]:
# Experiment 9 Classification Report (Regular Dataset - 7 OM combined)
# Result from 101 samples 
# P Labeled 0 and NP labeled 100 from RNN Results




import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-9-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[40]]
              precision    recall  f1-score   support

          NP       1.00      1.00      1.00        40

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



[Result 10 CSV File](#https://github.com/rashedhasan090/OM-ML_Research/blob/main/January%202023%20Analysis/New%20Analysis/sampleset/classification%20report/Result-10-c.csv 
)

In [39]:
# Experiment 10 Classification Report (Regular Dataset - 7 OM combined)
# Result from 101 samples 
# P Labeled 3 and NP labeled 97 from RNN Results



import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
data = pd.read_csv("Result-10-c.csv")
data = data[["Label", "OM_Data"]]
x = np.array(data["OM_Data"])
y = np.array(data["Label"])
cv = CountVectorizer()
X = cv.fit_transform(x) # Fit the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.40, random_state=42)
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(X_test)
# Classification Report
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, predictions))
from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

[[38  0]
 [ 2  0]]
              precision    recall  f1-score   support

          NP       0.95      1.00      0.97        38
           P       0.00      0.00      0.00         2

    accuracy                           0.95        40
   macro avg       0.47      0.50      0.49        40
weighted avg       0.90      0.95      0.93        40



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
